// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.darkhorse.getsporty.domain;

import com.darkhorse.getsporty.domain.Coach;
import org.springframework.data.annotation.Persistent;

privileged aspect Coach_Roo_Mongo_Entity {
    
    declare @type: Coach: @Persistent;
    
}
